name: login_fresh
description: LoginFresh is a user-friendly design where you can incorporate functionalities such as signUp, reset password or login with social networks
version: 2.0.0
authors:
  - Cristhian Hernandez <cristhian.hernandez@softnux.io>

homepage: https://github.com/Krysthyan/login_fresh

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  another_flushbar: ^1.10.24
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/images_login_fresh_34_/
